import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ClientLayout from './ClientLayout';
import { Toaster } from '@/components/ui/sonner';
import ReduxProvider from './ReduxProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Blog Post',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <ReduxProvider>
            <ClientLayout>{children}</ClientLayout>
            <Toaster />
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
